### PR TITLE
Implementing Restful API

### PR DESCRIPTION
**Pull request by LKDevelopment**
- [X] Add fundamental Controller and Routes
- [x] Add Tests
- [X] Allow Users to change the Controller, Middleware and Routeprefix

### CODE REVIEW

**Comment by LKDevelopment** [comment]
@freekmurze i think this PR is ready, if you merge it would you make the StyleCI PR or should i make it per hand?

**Comment by freekmurze** [comment]
Hi, after giving it some more thought I'd like only the uptime monitor itself in this package. The API could be a separate one. 

I also want to only maintain code that I use myself. This API is probably something that I'll not need myself in the foreseeable future.

Could you please create a new package under your own vendor? I'd be more that happy to refer to your API package in the readme.

**Comment by LKDevelopment** [comment]
Sure, i will create it as an new Package.

**Comment by LKDevelopment** [comment]
So it is complete implemented now in a new package https://github.com/LKDevelopment/laravel-uptime-monitor-api

**Comment by freekmurze** [comment]
Nice! If I may make a humble suggestion: add some badges to your readme so your potential users can see the code quality is ok and the tests are running fine.

**Comment by LKDevelopment** [comment]
@freekmurze Thank you, i've added some badges.

**Pull request closed without merging**
